import "./globals.css"
import "material-icons/iconfont/material-icons.css"
import ThemeChanger from "@/contexts/ThemeChanger"
import ThemeProvider from "@/contexts/ThemeProvider"
import { cookies } from "next/headers"
import { ThemeType, isIncludesType } from "@/utils/CommonTypes"
import { GoogleOAuthProvider } from "@react-oauth/google"
import { AuthProvider } from "@/components/AuthProvider"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const nowSetTheme = (await cookies()).get("theme")?.value
  const theme = () => {
    if (nowSetTheme && isIncludesType(ThemeType, nowSetTheme)) {
      return nowSetTheme
    }
    return ThemeType.NONE
  }
  const googleClientId = process.env.AUTH_GOOGLE_ID!

  return (
    <html lang="ja">
      <body>
        <div className="drawer">
          <input id="my-drawer-3" type="checkbox" className="drawer-toggle" />
          <div className="drawer-content flex flex-col">
            {/* Navbar */}
            <AuthProvider>
              <GoogleOAuthProvider clientId={googleClientId}>
                <ThemeProvider selectedTheme={theme()}>
                  <ThemeChanger>
                    {/* Page content here */}
                    {children}
                  </ThemeChanger>
                </ThemeProvider>
              </GoogleOAuthProvider>
            </AuthProvider>
          </div>
          <div className="drawer-side">
            <label
              htmlFor="my-drawer-3"
              aria-label="close sidebar"
              className="drawer-overlay"
            ></label>
            <ul className="menu bg-base-200 min-h-full w-80 p-4">
              {/* Sidebar content here */}
              <li>
                <a>Sidebar Item 1</a>
              </li>
              <li>
                <a>Sidebar Item 2</a>
              </li>
            </ul>
          </div>
        </div>
      </body>
    </html>
  )
}
